# Transformers inference service (for embeddings)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transformers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transformers
  template:
    metadata:
      labels:
        app: transformers
    spec:
      containers:
      - name: transformers
        image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: transformers
spec:
  selector:
    app: transformers
  ports:
  - port: 8080
    targetPort: 8080
