# ConfigMap for Weaviate settings
apiVersion: v1
kind: ConfigMap
metadata:
  name: weaviate-config
data:
  QUERY_DEFAULTS_LIMIT: "20"
  AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
  PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
  ENABLE_MODULES: "text2vec-transformers"
  TRANSFORMERS_INFERENCE_API: "http://transformers:8080"
